# prod compose file
# includes fossbilling, mysql, pub/sub
# rabbitmq is not included here, must be available externally at RABBITMQ_HOST
networks:
  billing_net:
    driver: bridge
  attendify_net:
    external: true

services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 30056:80
    volumes:
      - fossbilling:/var/www/html
    networks:
      - billing_net
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - billing_net
  billing-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer.prod
    depends_on:
      - rabbitmq
      - fossbilling
      - mysql
    restart: always
    networks:
      - attendify_net
      - billing_net
    env_file:
      - .env
  billing-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer.prod
    depends_on:
      - rabbitmq
      - fossbilling
      - mysql
    restart: always
    networks:
      - attendify_net
      - billing_net
    env_file:
      - .env
      
volumes:
  fossbilling: