# use official php image
FROM php:8.3-cli

# install dependecies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libpq-dev \
    librabbitmq-dev \
    curl \
    libcurl4-openssl-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-install \
    sockets \
    curl \
    pdo \
    pdo_mysql \
    pdo_pgsql \
    pcntl \
    && pecl install amqp && docker-php-ext-enable amqp

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# set work directory
WORKDIR /app

# copy composer files
COPY producers/composer.json producers/composer.lock ./producers/

# install composer dependencies
RUN composer install --prefer-dist --no-progress --working-dir=/app/producers

# copy producers code
COPY producers/ /app/producers/

# copy utility files
COPY parser.php /app

# grant permissions
# RUN chown -R www-data:www-data /app

# set entrypoint
CMD ["php", "./producers/user_producer.php"]