networks:
  billing_net:
    driver: bridge
  attendify_net:
    external: true

services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - 30056:80
    volumes:
      - fossbilling:/var/www/html
    networks:
      - billing_net
  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      # - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - billing_net
  billing-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - rabbitmq
      - fossbilling
      - mysql
    restart: always
    networks:
      - attendify_net
      - billing_net
  billing-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    depends_on:
      - rabbitmq
      - fossbilling
      - mysql
    networks:
      - attendify_net
      - billing_net
  billing-heartbeat:
    build:
      context: .
      dockerfile: Dockerfile.heartbeat
    depends_on:
      - fossbilling
      - mysql
      - billing-producer
      - billing-consumer
    networks:
      - attendify_net
      - billing_net

volumes:
  fossbilling: