# TODO: use reverse proxy for security
include:
  - docker-compose.billing.yml
networks:
  attendify_net:
    external: true
# rabbitmq does not support secrets
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: some-rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: attendify
      RABBITMQ_DEFAULT_VHOST: attendify
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - attendify_net