services:
  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - "90:80"  # Changed to 8080 to avoid conflicts with other services
    volumes:
      - fossbilling_data:/var/www/html
      - ../consumers:/var/www/html/consumers
      - ../producers:/var/www/html/producers
      - ./crontab:/etc/cron.d/fossbilling-cron
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mysql
      - rabbitmq
      
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: fossbilling
      DB_USER: fossbilling
      DB_PASS: fossbilling
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: fossbilling
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

volumes:
  fossbilling_data:
  mysql_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge