name: FOSSBilling CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main  # Trigger the pipeline on pushes to the "main" or "def" branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runs the CI jobs on Ubuntu

    steps:
      - name: Checkout Repository #Fetch latest code from repository
        uses: actions/checkout@v3
      
      - name: "Debug: Docker" #Debugging step to display Docker information
        run: docker info
        
      - name: "Debug: System Info" #Extra debugging step to display system status
        run: |
          whoami 
          groups
          hostname
          pwd
          ls

      - name: Build Docker Image for FOSSBilling 
        run: |
          docker compose up --build

      # run: |
      #   docker-compose up -d
      #  sleep 10  # Wait for containers to start
      # docker ps  # List running containers
      #docker-compose down # stops and removes container after testing

  # deploy:
  #   needs: build  
  #   runs-on: development VM

  #   steps:
  #     - name: deploy fossbilling
  #       run: |
  #           git pull origin main  # Pull the latest changes from the repository
  #           docker-compose up --build -d  # Rebuild and restart containers
  #           docker system prune -f  # Clean up old images

  test-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Run Simple PHP Script
        run: |
          echo "Running test.php"
          php Test/UnitTest/test.php
