name: FOSSBilling CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: "Debug: Docker"
        run: docker info
        
      - name: "Debug: System Info"
        run: |
          whoami 
          groups
          hostname
          pwd
          ls

      - name: Build Docker Images
        run: |
          docker compose -f docker/docker-compose.yml build

      - name: Run and Test Docker Containers
        run: |
          docker compose -f docker/docker-compose.yml up -d
          sleep 10  # Wait for containers to start
          docker ps  # List running containers
          docker compose -f docker/docker-compose.yml down # stops and removes container after testing

  test-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Run Simple PHP Script
        run: |
          echo "Running test.php"
          php Test/UnitTest/Test.php
