name:  FOSSBilling Pre-Prod Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pre-prod

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v3

      - name:  Build Docker Images
        run: |
          docker build -f docker/Dockerfile.consumer.prod -t fossbilling-consumer:latest .
          docker build -f docker/Dockerfile.producer.prod -t fossbilling-producer:latest .

      - name:  Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name:  Deploy to Server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no student@${{ secrets.DNS_NAME }} << 'EOF'
            set -e
            cd /root/billing/attendify-billing
            git pull origin release
            docker compose -f docker-compose.prod.yml up -d --build
          EOF
